# sqoop export --connect "jdbc:mysql://localhost/indigenous" --username training --password training --table lng_id --export-dir /user/training/assignment2/austlang_rdb/lng_id --fields-terminated-by '\t' --m 1
# sqoop export --connect "jdbc:mysql://localhost/indigenous" --username training --password training --table lng_name --columns lng_name  --export-dir /user/training/assignment2/austlang_rdb/lng_name --fields-terminated-by '\t' --m 1
sqoop export --connect "jdbc:mysql://localhost/indigenous" --username training --password training --table lng_synonym --columns lng_synonym  --export-dir /user/training/assignment2/austlang_rdb/lng_synonym --fields-terminated-by '\t' --m 1
# sqoop export --connect "jdbc:mysql://localhost/indigenous" --username training --password training --table lng_thl --columns lng_thl  --export-dir /user/training/assignment2/austlang_rdb/lng_thl --fields-terminated-by '\t' --m 1
# sqoop export --connect "jdbc:mysql://localhost/indigenous" --username training --password training --table lng_thp --columns lng_thp  --export-dir /user/training/assignment2/austlang_rdb/lng_thp --fields-terminated-by '\t' --m 1
# sqoop export --connect "jdbc:mysql://localhost/indigenous" --username training --password training --table lng_st --columns lng_st  --export-dir /user/training/assignment2/austlang_rdb/lng_st --fields-terminated-by '\t' --m 1


# sqoop export --connect "jdbc:mysql://localhost/indigenous" --username training --password training --table rel_code_name --columns lng_code,lng_name --export-dir /user/training/assignment2/austlang_rdb/rel_code_name --fields-terminated-by '\t' --m 1
# sqoop export --connect "jdbc:mysql://localhost/indigenous" --username training --password training --table rel_code_synonym --columns lng_code,lng_synonym --export-dir /user/training/assignment2/austlang_rdb/rel_code_synonym --fields-terminated-by '\t' --m 1
# sqoop export --connect "jdbc:mysql://localhost/indigenous" --username training --password training --table rel_code_thl --columns lng_code,lng_thl --export-dir /user/training/assignment2/austlang_rdb/rel_code_thl --fields-terminated-by '\t' --m 1
# sqoop export --connect "jdbc:mysql://localhost/indigenous" --username training --password training --table rel_code_thp --columns lng_code,lng_thp --export-dir /user/training/assignment2/austlang_rdb/rel_code_thp --fields-terminated-by '\t' --m 1
# sqoop export --connect "jdbc:mysql://localhost/indigenous" --username training --password training --table rel_code_st --columns lng_code,lng_st --export-dir /user/training/assignment2/austlang_rdb/rel_code_st --fields-terminated-by '\t' --m 1
